# Generated by Django 5.2.2 on 2026-03-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='users.profile', verbose_name='Заблокированные пользователи'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество подписчиков'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество подписок'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество друзей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, help_text='Ссылка на GitHub профиль', verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ideas_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество идей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ваш Instagram username', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний визит'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Ссылка на LinkedIn профиль', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_friends',
            field=models.CharField(choices=[('public', 'Публичный - видят все'), ('friends', 'Только друзья'), ('private', 'Приватный - только я')], default='public', max_length=10, verbose_name='Кто видит список друзей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_ideas',
            field=models.CharField(choices=[('public', 'Публичный - видят все'), ('friends', 'Только друзья'), ('private', 'Приватный - только я')], default='public', max_length=10, verbose_name='Кто видит идеи'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_profile',
            field=models.CharField(choices=[('public', 'Публичный - видят все'), ('friends', 'Только друзья'), ('private', 'Приватный - только я')], default='public', max_length=10, verbose_name='Кто видит профиль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('away', 'Отошел')], default='offline', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ваш Telegram username (без @)', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, help_text='Ваш Twitter username', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='Ваш личный сайт или блог', verbose_name='Веб-сайт'),
        ),
    ]
