# Generated by Django 5.2.2 on 2026-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='audio',
            field=models.FileField(blank=True, help_text='Загрузите MP3 файл (максимум 10MB)', null=True, upload_to='audio/', verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='idea',
            name='audio_title',
            field=models.CharField(blank=True, help_text='Например: "Bohemian Rhapsody - Queen"', max_length=200, null=True, verbose_name='Название трека'),
        ),
    ]
