# Generated by Django 5.2.2 on 2026-03-19 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_audio_idea_audio_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Идея', 'verbose_name_plural': 'Идеи'},
        ),
        migrations.RemoveField(
            model_name='idea',
            name='parent',
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
